name: 
channels:
  - conda-forge
  - pkgs/main
  - pkgs/r
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - _r-mutex=1.0.0=anacondar_1
  - _sysroot_linux-64_curr_repodata_hack=3=haa98f57_10
  - abseil-cpp=20211102.0=hd4dd3e8_0
  - affine=2.3.0=pyhd3eb1b0_0
  - aiobotocore=2.12.2=pyhd8ed1ab_0
  - aiohttp=3.7.4.post0=py39h3811e60_1
  - aioitertools=0.12.0=pyhd8ed1ab_1
  - annotated-types=0.6.0=py39h06a4308_0
  - arrow=1.4.0=py39h06a4308_0
  - arrow-cpp=11.0.0=h374c478_2
  - asciitree=0.3.3=py_2
  - asttokens=2.0.5=pyhd3eb1b0_0
  - async-timeout=3.0.1=py_1000
  - attrs=24.2.0=py39h06a4308_0
  - aws-c-common=0.6.8=h5eee18b_1
  - aws-c-event-stream=0.1.6=h6a678d5_6
  - aws-checksums=0.1.11=h5eee18b_2
  - aws-sdk-cpp=1.8.185=h721c034_1
  - backcall=0.2.0=pyhd3eb1b0_0
  - beautifulsoup4=4.12.3=py39h06a4308_0
  - binaryornot=0.4.4=pyhd3eb1b0_1
  - binutils_impl_linux-64=2.40=h5293946_0
  - binutils_linux-64=2.40.0=hc2dff05_2
  - blas=1.0=openblas
  - blinker=1.9.0=py39h06a4308_0
  - blosc=1.21.3=h6a678d5_0
  - bokeh=3.4.3=py39h2f386ee_0
  - boost-cpp=1.82.0=hdb19cb5_2
  - botocore=1.34.51=pyge38_1234567_0
  - bottleneck=1.3.7=py39ha9d4c09_0
  - bounded-pool-executor=0.0.3=pyhd8ed1ab_0
  - branca=0.6.0=py39h06a4308_0
  - brokenaxes=0.4.2=pyhd8ed1ab_0
  - brotli=1.0.9=h5eee18b_8
  - brotli-bin=1.0.9=h5eee18b_8
  - brotli-python=1.0.9=py39h6a678d5_8
  - bwidget=1.9.16=h9eba36c_0
  - bzip2=1.0.8=h5eee18b_6
  - c-ares=1.19.1=h5eee18b_0
  - ca-certificates=2024.9.24=h06a4308_0
  - cachetools=5.5.1=py39h06a4308_0
  - cairo=1.16.0=hb05425b_5
  - cartopy=0.22.0=py39h1128e8f_0
  - cattrs=24.1.2=py39h06a4308_0
  - cdsapi=0.7.5=pyhd8ed1ab_1
  - certifi=2024.8.30=py39h06a4308_0
  - cffi=1.17.1=py39h1fdaa30_1
  - cfitsio=3.470=h5893167_7
  - cftime=1.6.2=py39h7deecbd_0
  - chardet=4.0.0=py39hf3d152e_3
  - charset-normalizer=3.3.2=pyhd3eb1b0_0
  - click=8.1.7=py39h06a4308_0
  - click-plugins=1.1.1=pyhd3eb1b0_0
  - cligj=0.7.2=pyhd3eb1b0_0
  - cloudpickle=3.0.0=py39h06a4308_0
  - comm=0.2.1=py39h06a4308_0
  - contourpy=1.2.0=py39hdb19cb5_0
  - cookiecutter=2.6.0=py39h06a4308_1
  - cryptography=44.0.1=py39h7825ff9_0
  - curl=8.9.1=hdbd6064_0
  - cycler=0.11.0=pyhd3eb1b0_0
  - cyrus-sasl=2.1.28=h52b45da_1
  - cytoolz=0.12.2=py39h5eee18b_0
  - dask=2024.5.0=py39h06a4308_0
  - dask-core=2024.5.0=py39h06a4308_0
  - dask-expr=1.1.0=py39h06a4308_0
  - datapi=0.2.0=pyhd8ed1ab_0
  - dbus=1.13.18=hb2f20db_0
  - debugpy=1.6.7=py39h6a678d5_0
  - decorator=5.1.1=pyhd3eb1b0_0
  - defusedxml=0.7.1=pyhd3eb1b0_0
  - distributed=2024.5.0=py39h06a4308_0
  - earthaccess=0.12.0=pyhd8ed1ab_0
  - eofs=1.4.1=pyhd8ed1ab_1
  - esgf-pyclient=0.3.1=pyhd8ed1ab_5
  - et_xmlfile=1.1.0=py39h06a4308_0
  - exceptiongroup=1.2.0=py39h06a4308_0
  - executing=0.8.3=pyhd3eb1b0_0
  - expat=2.6.3=h6a678d5_0
  - fasteners=0.16.3=pyhd3eb1b0_0
  - fastprogress=1.0.0=pyhb85f177_0
  - fiona=1.9.5=py39h1128e8f_0
  - flake8=7.1.1=py39h06a4308_0
  - flexcache=0.3=pyhd8ed1ab_1
  - flexparser=0.4=pyhd8ed1ab_1
  - folium=0.14.0=py39h06a4308_0
  - fontconfig=2.14.1=h55d465d_3
  - fonttools=4.51.0=py39h5eee18b_0
  - freetype=2.12.1=h4a9f257_0
  - freexl=2.0.0=hf309648_0
  - fribidi=1.0.10=h7b6447c_0
  - fsspec=2025.3.2=pyhd8ed1ab_0
  - gcc_impl_linux-64=11.2.0=h1234567_1
  - gcc_linux-64=11.2.0=h5c386dc_2
  - gcsfs=2025.3.2=pyhd8ed1ab_0
  - gdal=3.6.2=py39h0daa840_6
  - geopandas=0.14.2=py39h06a4308_0
  - geopandas-base=0.14.2=py39h06a4308_0
  - geos=3.8.0=he6710b0_0
  - geotiff=1.7.0=h2a26cda_3
  - gflags=2.2.2=h6a678d5_1
  - gfortran_impl_linux-64=11.2.0=h1234567_1
  - gfortran_linux-64=11.2.0=hc2dff05_2
  - giflib=5.2.2=h5eee18b_0
  - glib=2.78.4=h6a678d5_0
  - glib-tools=2.78.4=h6a678d5_0
  - glog=0.5.0=h6a678d5_1
  - google-api-core=2.24.2=py39h06a4308_0
  - google-auth=2.38.0=py39h06a4308_1
  - google-auth-oauthlib=1.2.1=py39h06a4308_0
  - google-cloud-core=2.4.3=py39h06a4308_0
  - google-cloud-storage=3.1.0=py39h06a4308_0
  - google-crc32c=1.6.0=py39h5eee18b_0
  - google-resumable-media=2.7.2=py39h06a4308_0
  - googleapis-common-protos=1.69.2=py39h06a4308_0
  - graphite2=1.3.14=h295c915_1
  - grpc-cpp=1.48.2=he1ff14a_1
  - gst-plugins-base=1.14.1=h6a678d5_1
  - gstreamer=1.14.1=h5eee18b_1
  - gxx_impl_linux-64=11.2.0=h1234567_1
  - gxx_linux-64=11.2.0=hc2dff05_2
  - h5netcdf=1.2.0=py39h06a4308_0
  - h5py=3.12.1=py39hc0802c4_0
  - harfbuzz=10.2.0=hf296adc_0
  - hdf4=4.2.13=h3ca952b_2
  - hdf5=1.12.1=h2b7332f_3
  - heapdict=1.0.1=pyhd3eb1b0_0
  - icu=73.1=h6a678d5_0
  - idna=3.7=py39h06a4308_0
  - importlib-metadata=7.0.1=py39h06a4308_0
  - importlib-resources=6.4.0=pyhd8ed1ab_0
  - importlib_metadata=7.0.1=hd3eb1b0_0
  - importlib_resources=6.4.0=py39h06a4308_0
  - iniconfig=1.1.1=pyhd3eb1b0_0
  - intake=2.0.7=py39h06a4308_0
  - intake-esm=2023.11.10=pyhd8ed1ab_0
  - ipykernel=6.29.5=py39h06a4308_0
  - ipython=8.15.0=py39h06a4308_0
  - itsdangerous=2.2.0=py39h06a4308_0
  - jedi=0.19.1=py39h06a4308_0
  - jinja2=3.1.4=py39h06a4308_0
  - jmespath=1.0.1=pyhd8ed1ab_1
  - joblib=1.4.2=py39h06a4308_0
  - jpeg=9e=h5eee18b_3
  - json-c=0.16=h5eee18b_0
  - jupyter_client=8.6.0=py39h06a4308_0
  - jupyter_core=5.7.2=py39h06a4308_0
  - kealib=1.5.0=hd940352_1
  - kernel-headers_linux-64=3.10.0=h57e8cba_10
  - kiwisolver=1.4.4=py39h6a678d5_0
  - krb5=1.20.1=h143b758_1
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.40=h12ee557_0
  - legacy-cgi=2.6.3=pyhc52e323_1
  - lerc=3.0=h295c915_0
  - libboost=1.82.0=h109eef0_2
  - libbrotlicommon=1.0.9=h5eee18b_8
  - libbrotlidec=1.0.9=h5eee18b_8
  - libbrotlienc=1.0.9=h5eee18b_8
  - libclang=14.0.6=default_hc6dbbc7_1
  - libclang13=14.0.6=default_he11475f_1
  - libcrc32c=1.1.2=h6a678d5_0
  - libcups=2.4.2=h2d74bed_1
  - libcurl=8.9.1=h251f7ec_0
  - libdeflate=1.17=h5eee18b_1
  - libedit=3.1.20230828=h5eee18b_0
  - libev=4.33=h7f8727e_1
  - libevent=2.1.12=hdbd6064_1
  - libffi=3.4.4=h6a678d5_1
  - libgcc=15.1.0=h767d61c_3
  - libgcc-devel_linux-64=11.2.0=h1234567_1
  - libgcc-ng=15.1.0=h69a702a_3
  - libgdal=3.6.2=hd4d5da2_6
  - libgfortran-ng=11.2.0=h00389a5_1
  - libgfortran5=11.2.0=h1234567_1
  - libglib=2.78.4=hdc74915_0
  - libgomp=15.1.0=h767d61c_3
  - libiconv=1.16=h5eee18b_3
  - libkml=1.3.0=h096b73e_7
  - libllvm14=14.0.6=hecde1de_4
  - libnetcdf=4.8.1=h14805e7_4
  - libnghttp2=1.57.0=h2d74bed_0
  - libopenblas=0.3.21=h043d6bf_0
  - libpng=1.6.39=h5eee18b_0
  - libpq=12.17=hdbd6064_0
  - libprotobuf=3.20.3=he621ea3_0
  - libsodium=1.0.18=h7b6447c_0
  - libspatialindex=1.9.3=h2531618_0
  - libspatialite=5.1.0=h040243e_1
  - libssh2=1.11.0=h251f7ec_0
  - libstdcxx-devel_linux-64=11.2.0=h1234567_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - libthrift=0.15.0=h1795dd8_2
  - libtiff=4.5.1=h6a678d5_0
  - libuuid=1.41.5=h5eee18b_0
  - libwebp-base=1.3.2=h5eee18b_1
  - libxcb=1.15=h7f8727e_0
  - libxkbcommon=1.0.1=h097e994_2
  - libxml2=2.13.1=hfdd30dd_2
  - libzip=1.8.0=h6ac8c49_1
  - locket=1.0.0=py39h06a4308_0
  - lz4=4.3.2=py39h5eee18b_0
  - lz4-c=1.9.4=h6a678d5_1
  - make=4.2.1=h1bed415_1
  - mapclassify=2.5.0=py39h06a4308_0
  - markdown-it-py=2.2.0=py39h06a4308_1
  - markupsafe=2.1.3=py39h5eee18b_0
  - matplotlib=3.9.2=py39h06a4308_0
  - matplotlib-base=3.9.2=py39hbfdbfaf_0
  - matplotlib-inline=0.1.6=py39h06a4308_0
  - mccabe=0.7.0=pyhd3eb1b0_0
  - mdurl=0.1.2=py39h06a4308_0
  - metpy=1.6.3=pyhd8ed1ab_1
  - minizip=4.0.3=hf59b114_0
  - msgpack-python=1.0.3=py39hd09550d_0
  - multidict=6.0.2=py39hb9d737c_1
  - multimethod=2.0=pyhd8ed1ab_0
  - multiurl=0.3.2=pyhd8ed1ab_0
  - myproxyclient=2.1.1=pyhd8ed1ab_1
  - mysql=5.7.24=h721c034_2
  - nc-time-axis=1.4.1=pyhd8ed1ab_0
  - ncurses=6.4=h6a678d5_0
  - nest-asyncio=1.6.0=py39h06a4308_0
  - netcdf4=1.6.2=py39h89d13dc_0
  - networkx=3.2.1=py39h06a4308_0
  - nspr=4.35=h6a678d5_0
  - nss=3.89.1=h6a678d5_0
  - numcodecs=0.12.1=py39h2c38b39_0
  - numexpr=2.10.1=py39hd28fd6d_0
  - numpy=1.26.4=py39heeff2f4_0
  - numpy-base=1.26.4=py39h8a23956_0
  - oauthlib=3.2.2=py39h06a4308_0
  - openjpeg=2.5.2=he7f1fd0_0
  - openpyxl=3.1.5=py39h5eee18b_0
  - openssl=3.0.15=h5eee18b_0
  - orc=1.7.4=hb3bc3d3_1
  - packaging=24.1=py39h06a4308_0
  - pandas=2.2.2=py39h6a678d5_0
  - pango=1.50.7=h0fee60c_1
  - parso=0.8.3=pyhd3eb1b0_0
  - partd=1.4.1=py39h06a4308_0
  - patsy=1.0.1=py39h06a4308_0
  - pcre2=10.42=hebb0a14_1
  - pexpect=4.8.0=pyhd3eb1b0_3
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - pillow=10.4.0=py39h5eee18b_0
  - pint=0.24.4=pyhd8ed1ab_1
  - pip=24.2=py39h06a4308_0
  - pixman=0.40.0=h7f8727e_1
  - platformdirs=3.10.0=py39h06a4308_0
  - pluggy=1.5.0=py39h06a4308_0
  - ply=3.11=py39h06a4308_0
  - pooch=1.8.2=py39h06a4308_0
  - poppler=22.12.0=h9614445_3
  - poppler-data=0.4.11=h06a4308_1
  - pqdm=0.2.0=pyhd8ed1ab_1
  - proj=9.3.1=he5811b7_0
  - prompt-toolkit=3.0.43=py39h06a4308_0
  - proto-plus=1.26.1=py39h06a4308_0
  - protobuf=3.20.3=py39h6a678d5_0
  - psutil=5.9.0=py39h5eee18b_0
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - pure_eval=0.2.2=pyhd3eb1b0_0
  - pyarrow=11.0.0=py39h468efa6_1
  - pyasn1=0.4.8=pyhd3eb1b0_0
  - pyasn1-modules=0.2.8=py_0
  - pybind11-abi=4=hd3eb1b0_1
  - pycodestyle=2.12.1=py39h06a4308_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pydantic=2.8.2=py39h06a4308_0
  - pydantic-core=2.20.1=py39hb02cf49_0
  - pyflakes=3.2.0=py39h06a4308_0
  - pygments=2.15.1=py39h06a4308_1
  - pyjwt=2.10.1=py39h06a4308_0
  - pyopenssl=25.0.0=py39h06a4308_0
  - pyparsing=3.1.2=py39h06a4308_0
  - pyproj=3.6.1=py39h6370d16_0
  - pyqt=5.15.10=py39h6a678d5_0
  - pyqt5-sip=12.13.0=py39h5eee18b_0
  - pyshp=2.3.1=py39h06a4308_0
  - pysocks=1.7.1=py39h06a4308_0
  - pytest=8.3.4=py39h06a4308_0
  - python=3.9.20=he870216_1
  - python-cmr=0.13.0=pyhff2d567_1
  - python-dateutil=2.9.0post0=py39h06a4308_2
  - python-lmdb=1.4.1=py39h6a678d5_0
  - python-slugify=8.0.4=py39h06a4308_0
  - python-tzdata=2023.3=pyhd3eb1b0_0
  - python_abi=3.9=2_cp39
  - pytz=2024.1=py39h06a4308_0
  - pyyaml=6.0.2=py39h5eee18b_0
  - pyzmq=25.1.2=py39h6a678d5_0
  - qhull=2020.2=hdb19cb5_2
  - qt-main=5.15.2=h53bd1ea_10
  - r-base=4.3.1=h1ae530e_0
  - r-changepoint=2.2.4=r43h76d94ec_0
  - r-envcpt=1.1.3=r43h76d94ec_0
  - r-lattice=0.22_5=r43h76d94ec_0
  - r-mass=7.3_60=r43h76d94ec_0
  - r-zoo=1.8_12=r43h76d94ec_0
  - rasterio=1.3.10=py39hf289cab_0
  - re2=2022.04.01=h295c915_0
  - readline=8.2=h5eee18b_0
  - requests=2.32.3=py39h06a4308_0
  - requests-cache=1.2.0=py39h06a4308_0
  - requests-oauthlib=2.0.0=py39h06a4308_0
  - rich=14.2.0=py39h06a4308_0
  - rpy2=3.5.11=py39r43h356210d_0
  - rsa=4.7.2=pyhd3eb1b0_1
  - rtree=1.0.1=py39h06a4308_0
  - ruptures=1.1.9=py39h988be6c_2
  - s3fs=2025.3.2=pyhd8ed1ab_0
  - scikit-learn=1.5.1=py39h1128e8f_0
  - scipy=1.13.1=py39heeff2f4_0
  - setuptools=75.1.0=py39h06a4308_0
  - shapely=2.0.5=py39h006c72b_0
  - simplegeneric=0.8.1=py39h06a4308_2
  - sip=6.7.12=py39h6a678d5_0
  - siphon=0.9=pyhd8ed1ab_2
  - six=1.16.0=pyhd3eb1b0_1
  - snappy=1.2.1=h6a678d5_0
  - snuggs=1.4.7=pyhd3eb1b0_0
  - sortedcontainers=2.4.0=pyhd3eb1b0_0
  - soupsieve=2.5=py39h06a4308_0
  - sqlite=3.45.3=h5eee18b_0
  - stack_data=0.2.0=pyhd3eb1b0_0
  - statsmodels=0.14.4=py39h5eee18b_0
  - sysroot_linux-64=2.17=h57e8cba_10
  - tblib=1.7.0=pyhd3eb1b0_0
  - text-unidecode=1.3=pyhd3eb1b0_0
  - threadpoolctl=3.5.0=py39h2f386ee_0
  - tiledb=2.3.3=h77177df_3
  - tinynetrc=1.3.1=pyhd8ed1ab_0
  - tk=8.6.14=h39e8969_0
  - tktable=2.10=h3d55465_1
  - tomli=2.0.1=py39h06a4308_0
  - toolz=0.12.0=py39h06a4308_0
  - tornado=6.4.1=py39h5eee18b_0
  - tqdm=4.66.5=py39h2f386ee_0
  - traitlets=5.14.3=py39h06a4308_0
  - typing-extensions=4.11.0=py39h06a4308_0
  - typing_extensions=4.11.0=py39h06a4308_0
  - tzdata=2024b=h04d1e81_0
  - tzlocal=5.2=py39h06a4308_0
  - ujson=5.10.0=py39h6a678d5_1
  - unicodedata2=15.1.0=py39h5eee18b_0
  - uriparser=0.9.7=h5eee18b_0
  - url-normalize=1.4.3=py39h06a4308_0
  - urllib3=1.26.19=pyhd8ed1ab_0
  - utf8proc=2.6.1=h5eee18b_1
  - wcwidth=0.2.5=pyhd3eb1b0_0
  - webob=1.8.9=pyhd8ed1ab_1
  - wheel=0.44.0=py39h06a4308_0
  - wrapt=1.14.1=py39hb9d737c_0
  - xarray=2023.6.0=py39h06a4308_0
  - xerces-c=3.2.4=h6a678d5_1
  - xyzservices=2022.9.0=py39h06a4308_1
  - xz=5.4.6=h5eee18b_1
  - yaml=0.2.5=h7b6447c_0
  - yarl=1.7.2=py39hb9d737c_2
  - zarr=2.13.3=py39h06a4308_0
  - zeromq=4.3.5=h6a678d5_0
  - zict=3.0.0=py39h06a4308_0
  - zipp=3.20.2=py39h06a4308_0
  - zlib=1.2.13=h5eee18b_1
  - zstd=1.5.6=hc292b87_0
  - pip:
    - SW-trends==0.1.0
    - esgf-pyclient==0.3.1
    - humidity_trends==0.1.0

prefix: "/home/kmckinnon/.conda/envs/diurnal"
